# -*- coding: utf-8 -*-

__author__ = "Inès BENITO"

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Principale_ihm(object):
    def setupUi(self, Principale_ihm):
        Principale_ihm.setObjectName("Principale_ihm")
        Principale_ihm.resize(933, 879)
        Principale_ihm.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/players.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Principale_ihm.setWindowIcon(icon)
        self.Conteneur = QtWidgets.QWidget(Principale_ihm)
        self.Conteneur.setObjectName("Conteneur")
        self.Background = QtWidgets.QWidget(self.Conteneur)
        self.Background.setGeometry(QtCore.QRect(0, 10, 931, 781))
        self.Background.setStyleSheet("")
        self.Background.setObjectName("Background")
        self.SoundsCheckBox = QtWidgets.QCheckBox(self.Background)
        self.SoundsCheckBox.setGeometry(QtCore.QRect(660, 340, 171, 61))
        self.SoundsCheckBox.setStyleSheet("font: 25 14pt \"Bahnschrift Light\";\n"
                                          "color:white;\n"
                                          "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Settings/alarm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SoundsCheckBox.setIcon(icon1)
        self.SoundsCheckBox.setChecked(True)
        self.SoundsCheckBox.setObjectName("SoundsCheckBox")
        self.MusicCheckBox = QtWidgets.QCheckBox(self.Background)
        self.MusicCheckBox.setGeometry(QtCore.QRect(660, 280, 171, 61))
        self.MusicCheckBox.setMouseTracking(True)
        self.MusicCheckBox.setStyleSheet("font: 25 14pt \"Bahnschrift Light\";\n"
                                         "color:white;\n"
                                         "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Settings/music-player.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MusicCheckBox.setIcon(icon2)
        self.MusicCheckBox.setChecked(True)
        self.MusicCheckBox.setObjectName("MusicCheckBox")
        self.PlayersComboBox = QtWidgets.QComboBox(self.Background)
        self.PlayersComboBox.setGeometry(QtCore.QRect(650, 150, 191, 41))
        self.PlayersComboBox.setStyleSheet("font: 25 14pt \"Bahnschrift Light\";\n"
                                           "\n"
                                           "\n"
                                           "")
        self.PlayersComboBox.setObjectName("PlayersComboBox")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Settings/players.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PlayersComboBox.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Settings/single_player.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PlayersComboBox.addItem(icon4, "")
        self.widget = QtWidgets.QWidget(self.Background)
        self.widget.setGeometry(QtCore.QRect(0, 0, 931, 781))
        self.widget.setStyleSheet("background-image:url(:/Settings/vestiaire.png);")
        self.widget.setObjectName("widget")
        self.NewGameButton = QtWidgets.QPushButton(self.Background)
        self.NewGameButton.setEnabled(True)
        self.NewGameButton.setGeometry(QtCore.QRect(660, 630, 171, 61))
        self.NewGameButton.setMinimumSize(QtCore.QSize(81, 24))
        self.NewGameButton.setStyleSheet("font: 25 20pt \"Bahnschrift Light\";\n"
                                         "icon:none;")
        self.NewGameButton.setObjectName("NewGameButton")
        self.DifficultyComboBox = QtWidgets.QComboBox(self.Background)
        self.DifficultyComboBox.setGeometry(QtCore.QRect(650, 220, 191, 41))
        self.DifficultyComboBox.setStyleSheet("font: 25 14pt \"Bahnschrift Light\";\n"
                                              "\n"
                                              "\n"
                                              "")
        self.DifficultyComboBox.setObjectName("DifficultyComboBox")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Settings/star.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DifficultyComboBox.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Settings/star2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DifficultyComboBox.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Settings/star3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DifficultyComboBox.addItem(icon7, "")
        self.widget.raise_()
        self.SoundsCheckBox.raise_()
        self.MusicCheckBox.raise_()
        self.PlayersComboBox.raise_()
        self.NewGameButton.raise_()
        self.DifficultyComboBox.raise_()
        Principale_ihm.setCentralWidget(self.Conteneur)
        self.menubar = QtWidgets.QMenuBar(Principale_ihm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 933, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Principale_ihm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Principale_ihm)
        self.statusbar.setObjectName("statusbar")
        Principale_ihm.setStatusBar(self.statusbar)
        self.actionStart_new_game = QtWidgets.QAction(Principale_ihm)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/table-football.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart_new_game.setIcon(icon8)
        self.actionStart_new_game.setObjectName("actionStart_new_game")
        self.actionStats = QtWidgets.QAction(Principale_ihm)
        self.actionStats.setObjectName("actionStats")
        self.actionHelp = QtWidgets.QAction(Principale_ihm)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon9)
        self.actionHelp.setObjectName("actionHelp")
        self.actionQuit = QtWidgets.QAction(Principale_ihm)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/exitt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon10)
        self.actionQuit.setObjectName("actionQuit")
        self.actionStatistics = QtWidgets.QAction(Principale_ihm)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icons/bars-chart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStatistics.setIcon(icon11)
        self.actionStatistics.setObjectName("actionStatistics")
        self.actionCredits = QtWidgets.QAction(Principale_ihm)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Icons/copyright.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCredits.setIcon(icon12)
        self.actionCredits.setObjectName("actionCredits")
        self.menuFile.addAction(self.actionStart_new_game)
        self.menuFile.addAction(self.actionHelp)
        self.menuFile.addAction(self.actionStatistics)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionCredits)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Principale_ihm)
        self.actionQuit.triggered.connect(Principale_ihm.close)
        QtCore.QMetaObject.connectSlotsByName(Principale_ihm)

    def retranslateUi(self, Principale_ihm):
        _translate = QtCore.QCoreApplication.translate
        Principale_ihm.setWindowTitle(_translate("Principale_ihm", "Playground"))
        self.Background.setWhatsThis(_translate("Principale_ihm",
                                                "<html><head/><body><p><img src=\":/Settings/settings.png\"/></p></body></html>"))
        self.SoundsCheckBox.setText(_translate("Principale_ihm", "Sounds On"))
        self.MusicCheckBox.setText(_translate("Principale_ihm", "Music On"))
        self.PlayersComboBox.setItemText(0, _translate("Principale_ihm", "Two players"))
        self.PlayersComboBox.setItemText(1, _translate("Principale_ihm", "Single player"))
        self.NewGameButton.setText(_translate("Principale_ihm", "Start game"))
        self.NewGameButton.setShortcut(_translate("Principale_ihm", "Return"))
        self.DifficultyComboBox.setItemText(0, _translate("Principale_ihm", "Easy"))
        self.DifficultyComboBox.setItemText(1, _translate("Principale_ihm", "Medium"))
        self.DifficultyComboBox.setItemText(2, _translate("Principale_ihm", "Hard"))
        self.menuFile.setTitle(_translate("Principale_ihm", "File"))
        self.actionStart_new_game.setText(_translate("Principale_ihm", "Start new game"))
        self.actionStart_new_game.setShortcut(_translate("Principale_ihm", "Return"))
        self.actionStats.setText(_translate("Principale_ihm", "Statistics"))
        self.actionStats.setShortcut(_translate("Principale_ihm", "S"))
        self.actionHelp.setText(_translate("Principale_ihm", "Help"))
        self.actionHelp.setShortcut(_translate("Principale_ihm", "H"))
        self.actionQuit.setText(_translate("Principale_ihm", "Quit"))
        self.actionQuit.setShortcut(_translate("Principale_ihm", "Esc"))
        self.actionStatistics.setText(_translate("Principale_ihm", "Statistics"))
        self.actionStatistics.setShortcut(_translate("Principale_ihm", "S"))
        self.actionCredits.setText(_translate("Principale_ihm", "Credits"))


import images_rc
