# -*- coding: utf-8 -*-

__author__ = "Inès BENITO"

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Principale_ihm(object):

    def setupUi(self, Principale_ihm):
        Principale_ihm.setObjectName("Principale_ihm")
        Principale_ihm.resize(791, 791)
        Principale_ihm.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/players.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Principale_ihm.setWindowIcon(icon)
        self.Conteneur = QtWidgets.QWidget(Principale_ihm)
        self.Conteneur.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.Conteneur.setObjectName("Conteneur")
        self.widget = QtWidgets.QWidget(self.Conteneur)
        self.widget.setGeometry(QtCore.QRect(0, 0, 791, 791))
        self.widget.setStyleSheet("background-image:url(:/Accueil/acc.png);\n"
                                  "background-repeat: no repeat;\n")
        self.widget.setObjectName("widget")
        self.NewGameButton = QtWidgets.QPushButton(self.widget)
        self.NewGameButton.setEnabled(True)
        self.NewGameButton.setGeometry(QtCore.QRect(30, 80, 171, 61))
        self.NewGameButton.setMinimumSize(QtCore.QSize(81, 24))
        self.NewGameButton.setStyleSheet("font: 25 20pt \"Bahnschrift Light\";\n"
                                         "icon:none;")
        self.NewGameButton.setObjectName("NewGameButton")
        self.StatsButton = QtWidgets.QPushButton(self.widget)
        self.StatsButton.setGeometry(QtCore.QRect(60, 320, 111, 41))
        self.StatsButton.setStyleSheet("font: 25 12pt \"Bahnschrift Light\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/bars-chart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StatsButton.setIcon(icon1)
        self.StatsButton.setObjectName("StatsButton")
        self.HelpButton = QtWidgets.QPushButton(self.widget)
        self.HelpButton.setGeometry(QtCore.QRect(60, 260, 111, 41))
        self.HelpButton.setStyleSheet("font: 25 12pt \"Bahnschrift Light\";")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HelpButton.setIcon(icon2)
        self.HelpButton.setObjectName("HelpButton")
        self.QuitButton = QtWidgets.QPushButton(self.widget)
        self.QuitButton.setGeometry(QtCore.QRect(60, 480, 111, 41))
        self.QuitButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.QuitButton.setStyleSheet("font: 25 12pt \"Bahnschrift Light\";")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/exitt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QuitButton.setIcon(icon3)
        self.QuitButton.setObjectName("QuitButton")
        self.SettingsButton = QtWidgets.QPushButton(self.widget)
        self.SettingsButton.setGeometry(QtCore.QRect(60, 200, 111, 41))
        self.SettingsButton.setStyleSheet("font: 25 12pt \"Bahnschrift Light\";")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/settings-work-tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SettingsButton.setIcon(icon4)
        self.SettingsButton.setObjectName("SettingsButton")
        self.CreditsButton = QtWidgets.QPushButton(self.widget)
        self.CreditsButton.setGeometry(QtCore.QRect(60, 380, 111, 41))
        self.CreditsButton.setStyleSheet("font: 25 12pt \"Bahnschrift Light\";")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/copyright.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CreditsButton.setIcon(icon5)
        self.CreditsButton.setObjectName("CreditsButton")
        Principale_ihm.setCentralWidget(self.Conteneur)
        self.menubar = QtWidgets.QMenuBar(Principale_ihm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 837, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Principale_ihm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Principale_ihm)
        self.statusbar.setObjectName("statusbar")
        Principale_ihm.setStatusBar(self.statusbar)
        self.actionStart_new_game = QtWidgets.QAction(Principale_ihm)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/table-football.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart_new_game.setIcon(icon6)
        self.actionStart_new_game.setObjectName("actionStart_new_game")
        self.actionStats = QtWidgets.QAction(Principale_ihm)
        self.actionStats.setObjectName("actionStats")
        self.actionHelp = QtWidgets.QAction(Principale_ihm)
        self.actionHelp.setIcon(icon2)
        self.actionHelp.setObjectName("actionHelp")
        self.actionQuit = QtWidgets.QAction(Principale_ihm)
        self.actionQuit.setIcon(icon3)
        self.actionQuit.setObjectName("actionQuit")
        self.actionStatistics = QtWidgets.QAction(Principale_ihm)
        self.actionStatistics.setIcon(icon1)
        self.actionStatistics.setObjectName("actionStatistics")
        self.actionSettings = QtWidgets.QAction(Principale_ihm)
        self.actionSettings.setIcon(icon4)
        self.actionSettings.setObjectName("actionSettings")
        self.actionCredits = QtWidgets.QAction(Principale_ihm)
        self.actionCredits.setIcon(icon5)
        self.actionCredits.setObjectName("actionCredits")
        self.menuFile.addAction(self.actionStart_new_game)
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionHelp)
        self.menuFile.addAction(self.actionStatistics)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionCredits)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Principale_ihm)
        self.actionQuit.triggered.connect(Principale_ihm.close)
        self.QuitButton.clicked.connect(Principale_ihm.close)
        QtCore.QMetaObject.connectSlotsByName(Principale_ihm)

    def retranslateUi(self, Principale_ihm):
        _translate = QtCore.QCoreApplication.translate
        Principale_ihm.setWindowTitle(_translate("Principale_ihm", "Playground"))
        self.NewGameButton.setText(_translate("Principale_ihm", "Start game"))
        self.NewGameButton.setShortcut(_translate("Principale_ihm", "Return"))
        self.StatsButton.setText(_translate("Principale_ihm", "Statistics"))
        self.HelpButton.setText(_translate("Principale_ihm", "Help"))
        self.HelpButton.setShortcut(_translate("Principale_ihm", "H"))
        self.QuitButton.setText(_translate("Principale_ihm", "Quit"))
        self.QuitButton.setShortcut(_translate("Principale_ihm", "Esc"))
        self.SettingsButton.setText(_translate("Principale_ihm", "Settings"))
        self.CreditsButton.setText(_translate("Principale_ihm", "Credits"))
        self.menuFile.setTitle(_translate("Principale_ihm", "File"))
        self.actionStart_new_game.setText(_translate("Principale_ihm", "Start new game"))
        self.actionStart_new_game.setShortcut(_translate("Principale_ihm", "Return"))
        self.actionStats.setText(_translate("Principale_ihm", "Statistics"))
        self.actionStats.setShortcut(_translate("Principale_ihm", "S"))
        self.actionHelp.setText(_translate("Principale_ihm", "Help"))
        self.actionHelp.setShortcut(_translate("Principale_ihm", "H"))
        self.actionQuit.setText(_translate("Principale_ihm", "Quit"))
        self.actionQuit.setShortcut(_translate("Principale_ihm", "Esc"))
        self.actionStatistics.setText(_translate("Principale_ihm", "Statistics"))
        self.actionStatistics.setShortcut(_translate("Principale_ihm", "S"))
        self.actionSettings.setText(_translate("Principale_ihm", "Settings"))
        self.actionCredits.setText(_translate("Principale_ihm", "Credits"))


